### ISSUE TITLE
Some remarks

### ISSUE THREAD

**Issue by DanielStaegemann** [Polyhistor/BD-and-Microservices-#1]
- I uploaded a word file containing the new version of the search graphic. Is it in your opinion okay?
- I think the order of "3.1.8 Data synthesis" and "3.1.9 The found papers" should be swapped
- We used to have a table showing the 10 founds papers. It should be inserted again (there is already a tex file in the folder of the conference paper; not sure if it works though or if it is broken) after the new text I proposed below (so new 3.1.8). Further I think we should add the number of citations in ResearchGate and Google Scholar for each paper (2 new columns) (if the table is there and prepared, I can insert the numbers. that's probably the easiest way, isn't it?)
- behind 3.1.7 (so as new 3.1.8) the following text can be inserted to describe the forward and backward search :

To further increase the comprehensiveness of the review process, following the recommendation of Webster and Watson (TODO: REF to Webster&Watson 2002), the initial keyword search was amended with a forward and backward search. Here, for the identified ten papers it was examined by which papers they are cited and which papers they cite. This was performed between October 10, 2022 and October 20, 2022. While the backward search could simply be based on the reference lists given in the papers, the forward search was less unequivocal, because there are several sources with slightly varying information. To account for this, two different ones, namely Google Scholar and ResearchGate were used. However, both searches yielded no new results that sufficed the criteria applied in the initial search. Instead, the 538 papers (combined for all papers and both sources, not accounting for duplicates) found in the forward search comprised, inter alia, thesis works, preprints, studies that are not directly related to microservices, papers that are too short and papers that did not meet the quality criteria. Regarding the backward search, most of the utilized conference papers and journal articles with a focus on microservices were already captured by the initial search, further highlighting its comprehensiveness. In total for the ten papers, and not accounting for duplicates, there were 16 new entries mentioning microservices in the title that were, however, ultimately not relevant for the focus of this work. Therefore, the final set still consists of the ten contributions shown in (TODO: REF to the new table showing the 10 found papers).

What do you think?

**Comment by Polyhistor** [comment]
okay cool, here's a list of things I've done: 

1. Replaced PRISMA old flowchart with the new one 
2. Changed the order of 'data synthesis' and 'the found papers'.
3. Brought back the papers table 
4. Added your text
5. Added the citation 


There's still a typo in  that writing 'inter alia'. But yea this issue is done, look at the files and close if everything is okay.

**Comment by DanielStaegemann** [comment]
Some remarks:
1) at least the pdf still shows the old PRISMA flowchart
2) I have added the citations to table 3 (however, I'm not sure how it will look in the pdf version)
3) Do you think it makes sense to have a table that shows the inclusion/exclusion criteria? (I think we had one in the initital draft, didn't we?)
4) in 3.1.2 is a reference error for Table 1: "The exact keywords and search strategy used can be found at ??"
5) I think Table 3 would be best placed after the text of 3.1.8 (so directly before the 3.1.9 caption) 
6) "All ten publications have been published in 2018 or later, with three of them being published in 2022, which shows the timeliness of the topic. Eight of the ten papers were found via Scopus, whereas the remaining two have been identified through IEEE Xplore." should in my opinion then placed directly after Table 3 (and before 3.1.9)

**Comment by Polyhistor** [comment]
1. Updated the code to display the correct flowchart
2. This was already added by me 
3. I think the way it is presented is fine. 
4. fixd
5. repositioned table 3
6. moved the paragraph

**Comment by Polyhistor** [comment]
I think those two new columns you've added, makes it really hard to fit the table in one page... the information is not that critical as well... so I guess that's unnecessary. I've had to spend a lot of time making the old table fit within the margins of our template, adding two new columns makes is really challenging...

Another thing about Latex is that, when you add a new column, you've gotta make sure tabular format is accounting for it. This is defined in

`  \begin{tabular}{|p{4cm}|p{0.7cm}|p{0.8cm}|p{0.5cm}|p{2cm}|p{1cm}|p{0.5cm}|}`

so if you wanted to add two new columns, this should be changed to: 

`  \begin{tabular}{|p{4cm}|p{0.7cm}|p{0.8cm}|p{0.5cm}|p{2cm}|p{1cm}|p{0.5cm}|p{0.5cm}|p{0.5cm}|}}}`

if you only add the new columns in between hlines in actual data row, the table won't render.

**Comment by DanielStaegemann** [comment]
Another reason why I'll probably never like Latex :D

I guess we can omit the citation numbers. We have the total count so that should give the reader at least an idea.

In my opinion, it would be good to have Table 3 before 3.1.9 (so effectively swapping pages 8 and 9).
Besides that I think everything is fine and the issue can be closed afterwards

**Comment by Polyhistor** [comment]
That table is about the found papers, which is discussed in 3.1.9 ? the reference to it is in that sub-section as well.. Is there any reason the table should be in forward/backward search section ?

**Comment by DanielStaegemann** [comment]
The forward/backward search concludes the acquisition of the literature. Therefore, I think the table with the results should come in the end of it.
There is also a reference to the table. (However, the "still" in that sentence should be removed.)
But I agree in the sense that the sentence with the reference in the beginning of 3.1.9 should be deleted
