### ISSUE TITLE
comments

### ISSUE THREAD

**Issue by DanielStaegemann** [Polyhistor/BD-and-Microservices-#2]
- The PDF doesn't work so I had to look into texx and maybe I oversaw it, but we should reintroduce the more comprehensive background section we had in the initial draft (if I remember correctly).

- I think, if possible, we should try to include variability as a characteristic (since its also prominent in NIST)

- we might need to align the background section and the later use of the characteristics (e.g. include privacy in the background section)

**Comment by Polyhistor** [comment]
1. I think the background section is unnecessary now as both MS and BD are defined in introduction 
2. We really can't afford to add a characteristic at this point. This affects everything 
3. We are really not looking forward to increase the scope, as this paper has been in progress for 5-6 months
