### ISSUE TITLE
some Comments (up until the introduction + some random stuff)

### ISSUE THREAD

**Issue by DanielStaegemann** [Polyhistor/BD-and-Microservices-#3]
0) the background section from the onference's initial draft should be brought back (and paper+background should be aligned a bit to each other)
1) abstract: "will yield" --> maybe "have the potential to reveal" (since in theorey there might be a setting where nothing important is found)
2) abstract: "about the role" --> maybe "regarding the role"?
3) abstract: "and many strived" --> why past?
4) abstract: "According to the literature, it is estimated that only 13% of organizations" --> maybe change it as you did with the sentence in the ECIS paper
5) abstract: "study indicates that big data architecture" --> "study indicate that big data architectures"
6) abstract: "theories that explicates how microservices patterns could be useful for big data systems. These theories" --> I'm not sure what's better, "theories" or "hypotheses"

7) intro: "of this new material" --> maybe "of this new ressource"?
8) intro: "According to New Vantage Partners report in 2022," --> "According to a New Vantage Partners report from 2022,"?
9) intro: "BD projects. One area" --> maybe we could briefly mention technology selection (the dissertation topic of Matthias) as one other option
10) intro: "therefore, increase maintainability" --> "therefore, increases maintainability"
11) intro: "Another concept that has the potential to help with development of BD systems is the use of microservices (MS) architecture." --> "Another concept that has the potential to help with development of BD systems
is the use of microservices (MS) architecture.[REF: https://www.scitepress.org/PublicationsDetail.aspx?ID=vWEbHp0yvHM=&t=1 --> that REF is already used in the background section]"
12) intro: "The first SLR is conducted as part of this study to collect all MS patterns in the body of knowledge. The results of these SLRs are collected, captured and combined through thematic synthesis. As a result, various design theories are generated and validated through a semi-structured interview. The second SLR is done by [4] to find all BD reference architectures (RAs) available in the body of
knowledge and to point out architectural constructus and limitations." --> "The first SLR is conducted as part of this study to collect all MS patterns in the body of knowledge. The second SLR is done by [4] to find all BD reference architectures (RAs) available in the body of knowledge and to point out architectural constructus and limitations. The results of these SLRs are collected, captured and combined through thematic synthesis. As a result, various design theories are generated and validated through a semi-structured interview." (swap the order of sentences. further, three sentences in a row start with "the" and the next paragraph also, making it 4)
13) intro: "1) it provides an updated synopsis of the existing BD reference architectures," --> is that true? I think your IEEE Access paper does this and this paper merely mentions it. (However, I think in this paper, the other stuff should be described at least a bit more comprehensively, giving for exampole relevant numbers and maybe also the found list of papers or something along those lines)
14) Figure 1: there is a red line below "AISeL"

**Comment by Polyhistor** [comment]
1. I've reviewed the background section, I believe all the information in there is already provided in this study. I think the background section just makes this study a bit less focused and does not provide any critical piece of information.
2. We have for sure created theories here, design and kernel theories to be exact, not hypothesis. 
3. Technology selection could be mentioned, but we don't aim to make this paper longer or add any more work. I think only changes that are really critical to the gestalt of the study should be applied. This helps with focus. 
4. The rest of the issues are sorted.

**Comment by DanielStaegemann** [comment]
I think if we have no background section, we should probably include the (chosen) big data characteristics in the introduction. (where BD is discussed)

edit: or add like a haf-sentence highlighting that big data not only refers to huge amounts of data bt also their complexity

**Comment by Polyhistor** [comment]
Added two sentences defining big data and its characteristics
