### ISSUE TITLE
some comments (up until the methodology section)

### ISSUE THREAD

**Issue by DanielStaegemann** [Polyhistor/BD-and-Microservices-#4]
1) related: "and reported on experience" -->  "and reported on their experience"
2) related: "This study aims to provide with a general picture" --> "This study aims to provide a general picture"
3) related: "does not aim to explore MS patterns and their relationship to BD systems" --> maybe "does not aim to explore MS patterns and their relationship to BD systems in detail"?
4) related: "approached through a RA that absorbs" --> "approached through RAs that absorb"
5) related: "there is no study that aimed" --> in my opinion "by now there is no study that aims"
6) methodology: "it is consequently mandatory" --> maybe "it is consequently essential"?
7) methodology: "thematic synthesis proposed by" --> "thematic synthesis as proposed by"
8) first: "The first SLR, is designed" --> "The first SLR, which focusses on microservice patterns, is designed"
9) first: "conducted in the following steps" --> maybe "conducted in the following 14 steps"
10) first: "These steps are not direct mappings to the following sub-sections. Some..." --> maybe "However, these steps are not direct
mappings to the following sub-sections, since some..."
11) first: "To achieve this," --> maybe "Therefore,"
12) first: "used can be found at Table1." --> "used can be found at Table 1." (space between Table and 1 added)
13) first: "Inspired by PRISMA checklist" --> "Inspired by the PRISMA checklist"
14) first: I think the placement of Table 1 is not optimal (not sure though if it can be even done better), but with the re-introduction of the background section, everything will shift anyways
15) first: "5) Short papers (less than 6 pages)." --> it should be mentioned that it is 6 pages not counting references
16) first: "Quality of the evidence collected" --> in my opinion "The quality of the evidence collected"
17) first: "we developed a criteria made up of 7 elements." --> maybe "we developed a quality framework that comprises seven elements."?
18) first: "These criteria are informed by guidelines provided by Kitchenham [10] on empirical research in software engineering. These 7 criteria are discussed in Table 2." --> maybe "These criteria that are informed by guidelines provided by Kitchenham [10] on empirical research in software engineering are discussed in Table 2."
19) first: "informed by guidelines" --> not sure if "by guidelines" or "by the guidelines" is better
20) first: the red line in Figure 1 needs to be removed
21) first: "through IEEE Xplore." --> maybe "through IEEE Xplore. The distribution between conference papers and journal articles is equal."
22) first: "using the software Nvivo." --> I would add the version (I think 12) "using the software Nvivo 12."
23) second: "The second SLR is conducted by [4] on available BD RAs in academia and industry. This is comprehensive study that..." --> maybe "The second necessary SLR was already conducted by other authors who explored available BD RAs in academia and industry in a sufficient manner [4]. They presented a comprehensive study that... Therefore, we have foregone to perform an analogous SLR of our own because it wouldn't have yielded new findings."
24) second: "The findings from this SLR helped us shaped the requirements necessary for BD systems" --> "The findings from the consulted SLR helped us to determine the requirements that are relevant for BD systems."
25) second: "We do not explore this SLR in this paper, and aim to only discuss the results of it." --> "However, we do not further explore this SLR in our paper, and instead only discuss the results of it. Yet, we recommend to consult it for more details."

**Comment by Polyhistor** [comment]
1. Some changes are not applied as I found them not that necessary ( let me know if it was important and I'm failing to see ), these changes are as the following points: 5, 7, 10,11
2. Addressed the rest of the comments

**Comment by Polyhistor** [comment]
@DanielStaegemann Paper has been reviewed by me once, all the interviewee comments are added. All that it needs is your complete review of all sections and then I can submit it .

Also, I added the declaration part of the paper, which is mandatory for journal of big data. It requires us to tell who has done what and provide descriptions about ourselves as well, please have a read of those too and let me know if I missed something. 

If you realized all the figures are at the end of the paper, that's intentional ( it's the requirement of the journal ).

**Comment by DanielStaegemann** [comment]
the other points are not really super important, however:

7: I'm not native, but for me without the "as" would be "Cruzes and Dyba are the ones that came up with thematic synthesis as a concept at all", whereas with the "as" it would be "we apply thematic synthesis and for this we use the way Cruzes and Dyba proposed"

10: for me it reads better but again the "not being native" part comes into play :D

11: the previous sentence also starts with "to" and we could avoid it that way

**Comment by Polyhistor** [comment]
"Cruzes and Dyba are the ones that came up with thematic synthesis as a concept at all" -> that's exactly what happened. They have come up with the idea :P and we are using.... but I think either with 'as' or without the definition does not vary...

**Comment by Polyhistor** [comment]
I'll add the 'as' anyway

**Comment by Polyhistor** [comment]
Closing, as comments are addressed
