### ISSUE TITLE
Some comments (mostly up until before 4.2)

### ISSUE THREAD

**Issue by DanielStaegemann** [Polyhistor/BD-and-Microservices-#5]
1) Figure 1: still has the read underlining of AISeL

2) my bio:
"
Daniel Staegemann, born in 1989 in Berlin, studied computer science at Technical University Berlin (TUB). He received the master’s degree in 2017. He is currently pursuing the PhD degree with the Otto-von-Guericke University Magdeburg (OVGU), where he has been employed as a scientific researcher since 2018. In this time, he published over 50 research papers, many of these in prestigious outlets such as the Americas Conference on Information Systems (AMCIS), the Pacific Asia Conference on Information Systems (PACIS), the International Conference on Design Science Research in Information Systems and Technology (DESRIST), the International Conference on Business Information Systems (BIS), the Hawaii International Conference on System Sciences (HICSS), and IEEE Access. Besides being an author and speaker at conferences as well as a mini-track and workshop chair, he also regularly acts as a reviewer. His research interest is mainly focused on big data and the corresponding quality assurance, but also encompasses all other related topics.
"

3) contributions: "and have done the interviews" --> maybe "and conducted the interviews"

4) contributions: I would probably add something like "checking and revising of the manuscript" for both

5) Page 2: "The second SLR is done by [5] to find all BD reference architectures (RAs)" --> the abbreviation was already introduced in page 1

6) Second Review: "This is comprehensive study" --> in my opinion "This is a comprehensive study"

7) Results: "In this section, we present with three integral elements: 1) BD requirements, 2) MS patterns, 3) the mapping between the two and theories that emerged as a result." --> that's not true, the third topic is section 5 --> maybe: "In this section, the findings of the SLRs are used to deduce two integral elements for our research : 1) BD requirements, 2) MS patterns"

8) "Results" --> I'm not sure if this name isn't too generic. Maybe something like "Findings of the Literature Reviews" or something like this

9) 4.1: "from the result of our SLR" --> "from the result (or besser results?) of our SLR, it did not include"

10) 4.1: "To this end, we performed a lightweight literature review in the body of knowledge to realize three major elements: 1) the
type of requirements that we need, 2) an approach to categorizing the requirements, 3) presentation of these requirements." --> maybe "To this end, we performed a lightweight literature review in the body of knowledge that comprised three steps: 1) determine the type of requirements that we need, 2) develop an approach to categorize the requirements, 3) presentation of these requirements."

11) 4.1.1: maybe change the name to "Determine requirements" or something like that? 

12) 4.1.1: "Our primary focus is one functional and domain requirements" --> maybe "Thus, our primary focus is on
functional and domain requirements" (! on instead of one !) What do you mean by domain requirements? (especially since you refer to e.g., the banking sector in the contect of NFRs being not relevant)

13) 4.1.2: "These 5Vs are velocity, veracity, volume, Variety and Value" --> a) why are somme uppercase and some lowercase? b) I think we should have the same order here as for the following sub-sections (also putting the sub-section "Security and Privacy" as last)

14) 4.1.3.1: "Volume refers to addressing multitude " --> "Volume refers to addressing a multitude "

15) 4.1.3.1: Therefore, volume requirements are as following: ‘’ --> delete after the :

16) 4.1.3.2: "Velocity refers to addressing the rate at which data flows into system" --> "Velocity refers to the rate at which data flows into the system"

17) Since the text of velocity refers to variety, it should only come after the corresponding section (has to be reflected in comment 13)

18) 4.1.3.4: "Gleaning, crunching and extracting value from data, requires" --> "Gleaning, crunching and extracting value from data requires" (without the last comma)

19) 4.1.3: "These requirements are described in following sub-sections." --> We should add a sentence clarifying that not always all requirements apply to every system (e.g., Val-4 is not relevant for every system and so on)

20) 4.1.3.5: "(GDPR for example)" --> "(GDPR [REF] for example)" (add a REF for GDPR would be maybe good)

21) 4.1.3: I'm not sure if/how it can be fixed (so maybe we have to accept it and hope it's not criticized too harshly), but right now the way the requirements are derived is kind of a black box

**Comment by Polyhistor** [comment]
Addressed all comments. However two points need further clarification: 1

1. I did not quite understand point 17 
2. In regards to point 21, we are explaining that requirements are derived by doing a SLR On current BD RAs.... we can for sure improve this... by incorporating use cases as well.... but we assess  how much time that might take and if it's really worth it

**Comment by DanielStaegemann** [comment]
1.) The text regarding the velocity mentions variety in it. Therefore, I makes sense to have the explanation of variety before the one of velocity. (This should then be also reflected in the order in the sentence from point 13b)

2.) I mean that in terms of "How are the found papers turned into these requirements". So just explaining a bit more how your used approach for this was.

**Comment by Polyhistor** [comment]
1. done 
2. working on it

**Comment by DanielStaegemann** [comment]
1.) for me "4.1.3.2 Velocity" still comes before "4.1.3.3 Variety" despite the text for velocity referring to variety ("quickly
on one hand and handling the variety of data")

**Comment by Polyhistor** [comment]
yea I got your point. I realised I will have to change many areas in the evaluation as well if we swap these two characteristics... So I guess we can leave it as be... I don't think that would be that bad ?

**Comment by Polyhistor** [comment]
I left the order as is for now, since it's mapped in 4 other parts of the research. I don't think that's a critical issue. If you felt that's the case, please open another issue.
