### ISSUE TITLE
comments up to and including 4.2.5

### ISSUE THREAD

**Issue by DanielStaegemann** [Polyhistor/BD-and-Microservices-#6]
1) 4.2: "As a result of this SLR" -> maybe "As a result of the conducted SLR"

2) 4.2: too many sentences in the first paragraph start with "These"

3) 4.2: "These patterns can be found in" --> which papers are you referring too?

4) 4.2: "from Buschmann et al’s work" --> the dot after "al" is missing

5) 4.2: "This pattern description language has several elements that does" --> "This pattern description language has several elements that do"

6) 4.2: "provide a code example for each patterns" --> "provide a code example for each pattern"

7) 4.2: "Each pattern is discussed in following subsections in the order of context, problem, forces and solution. The starting paragraph of each pattern is the context, followed by the ‘problem’ sub-section that aims to illuminate on challenges through interrogatives, followed by the ‘solution’ sub-section that discuses better approach through the corresponding pattern." --> a) "forces" is omitted (as also stated in the sentence before this one) b) the two sentences are pretty redundant

8) 4.2.1: "practice management system for veterinarian, and is using microservices for different aspect of the system such as financial, medical, client and animal." --> a) "practice management system for veterinarians" b) "for different aspects" c) "such as financial, medical, client and animal related ones."

9) 4.2.1: "The animal micro-frotned needs the animal data, and financial micro-frotned" --> 2 times typo at frontend

10) 4.2.1: "How does the financial micro-frontend retrieves" --> "How does the financial micro-frontend retrieve"

11) 4.2.1: "backends? should" --> "backends? Should" (uppercase) --> the same apparently applies to all the other "Problem"-questions in 4.2. Furthermore, the are often spaces (that should be deleted) before the questionmarks (I don't think the current formatting is good)

12) 4.2.1: "does the financial micro-frontend gets" --> "does the financial micro-frontend get"

13) 4.2.2: " if an implementation of on team does not respect the specification" --> " if an implementation of one team does not respect the specification"

14) 4.2.2: " standardised interfaces which help" --> a) comma before the which b) help or helps goes both, depending on what it is referring too. Not sure though, which variant is better

15) 4.2.3: "deployed to various environment" --> "deployed to various environments"

16) 4.2.3: "This is part of CI/CD approach" --> "This is part of the CI/CD approach "

17) 4.2.3: "to capture bugs, and issues" --> "to capture bugs and issues" (without comma)

18) 4.2.3: " For instance there are testing, integration, pre-production and production environments" --> " For instance, there are testing, integration, pre-production, and production environments" (comma after instance; comma before and, since you generally did it in this paper)

19) 4.2.3: "several features flags" --> feature flags or features' flags ?

20) 4.2.3: "the number of applications grow" --> "the number of applications grows"

21) 4.2.3: "various class of services require" --> ""various classes of services require

22) 4.2.3: "On startup, application can" --> "the application" or "applications" or "an application"

23) 4.2.3: "This for example could happen in CMD command of Docker script" --> I think I would delete the sentence

24): 4.2.4: "expected to handle large number " --> I think "expected to handle a large number "

25): 4.2.4: "approach is for application" --> "approach is for applications"

26) 4.2.4: "This ensure that one blocking " --> "This ensures that one blocking "

27) 4.2.4: "not gonna have ripple effect" --> "not gonna have a ripple effect"

28) 4.2.4: "Requests loads vary at different times. During peak hours there might be many requests coming from various
sources. In addition, the processing required for different requests vary, and while some may be quite cheap, the other might be compute intensive." --> "One potential cause for such an issue is that requests' [possessive plural] loads can [new] vary at different times. During peak hours there might be many requests coming from various sources. In addition, the processing required for different requests varies [changed], and while some may be quite cheap, others [change] might be compute intensive."

29) 4.2.4: "Message queue system can be used" --> "A message queue system can be used"

30) 4.2.4: "which allows in" --> "which allows for" ?

31) 4.2.4: in solution there are 3 sentences in a row that start with "This"

32) 4.2.4: "This increase the" --> "This increases the"

33) 4.2.4: "consumer services unavailability" --> I think "a consumer service's unavailability"

34) 4.2.5: " synchronously calls another services" --> " synchronously calls another service"

35) 4.2.5: "there’s a chance" --> "there is a chance"

36) 4.2.5: "to avoid ripple effect" --> "to avoid a ripple effect"

37) 4.2.5: "fault resolution which allows system" --> "fault resolution, which allows a/the system" (comma, a/the)

38) 4.2.5: "failing requests reach a certain" --> "failing requests reaches a certain"

39) 4.2.5: " This pattern is usually implemented as a state machine that mimics the functionality of an electrical circuit breaker. This is usually" --> 2 times usually

40) 4.2.5: "where circuit breaker listens " --> "where the circuit breaker listens "

41) 4.2.5: "failing requests reach a certain" --> "failing requests reaches a certain"

42) 4.2.5: " that service is healthy" --> " that the service is healthy"

43) 4.2.5: "and circuit breaker switches to closed state" --> "and the circuit breaker switches to the closed state"

44) 4.2.5: "This pattern is displaed in Figure 6." --> "This pattern is displayed in Figure 6."

**Comment by Polyhistor** [comment]
All comments addressed
