### ISSUE TITLE
Some comments "Results" finished

### ISSUE THREAD

**Issue by DanielStaegemann** [Polyhistor/BD-and-Microservices-#7]
1) 4.2.6: "Microservices is comprising of large set of services" --> maybe "Microservice architectures often comprise a large set of services"

2) 4.2.6: "A request usually spans multiple services, and in the process something might go wrong, and bugs may occur" --> I think without commas, but I'm not sure

3) 4.2.6: "How to understand the root cause of issue if it’s spanning multiple services" -->"How to understand the root cause of an issue if it spans (maybe add: across) multiple services"

4) 4.2.6: "that retrieves logs from different services and compose them together" --> a) composes b) i think without "together"

5) 4.2.6: "This pattern is portrated in Figure 7." --> "This pattern is portrayed in Figure 7."

6) 4.2.7: "handle the miss match" --> in my opinion "handle the mismatch"

7) 4.2.7: "team ensure certain performance objective is met" --> I think "team ensure a certain performance objective is met" or "team ensure certain performance objectives are met"

8) 4.2.7: "separates reads and writes workloads" --> I think "separates read and write workloads" or "separates reads' and writes' workloads"

9) 4.2.7: " This is usually achieved through a message queue asynchronously" --> for me the structure sounds a bit weird

10) 4.2.7: " Having the command and query separated, simplifies modeling, development and maintenance of data stores" --> usually you had a comma before the and

11) 4.2.8: "Most services rely on some other services for data or functionality. Each service has its own domain model. Some of these services can be external services, some of these services can be internal legacy services, and some of them can be bleeding edge services." --> not an error but 8 times "service" in 3,5 lines is quite a lot

12) 4.2.8: " to account for legacy service’ interface" --> " to account for the legacy service’s interface"

13) 4.2.8: " Anti-corruption layer can" --> "The anti-corruption layer can"

14) 4.2.9: "a backend service needs to provides the " --> "a backend service needs to provide the "

15) 4.2.9: "A client can be the user browser, " --> "A client can be the user's browser, "

16) 4.2.9: "or an IOT device" --> "or an IoT device"

17) 4.2.9: "As the number of clients grow," --> "As the number of clients grows,"

18) 4.2.10: "Different processing can" --> I think "Different processings can"

19) 4.2.10: " command ‘ls’ into the command ‘grep’ or command ‘sed" --> maybe it would be good to add a very brief explanation in brackets after each of the commands?

20) 4.2.10: "By standardizing interface" --> maybe "By standardizing the interface" or "By standardizing the interfaces"?

21) 4.2.10: "be easily combined together " -> I think that a bit redundant, maybe just "be easily combined"

22) 4.2.10: " and maintainability increases" --> I think " and the maintainability increases"

23) 4.2.10: " This pattern is portrated at Figure 11." --> " This pattern is portrayed at Figure 11."

**Comment by Polyhistor** [comment]
Done
