### ISSUE TITLE
Some comments up until 6.4

### ISSUE THREAD

**Issue by DanielStaegemann** [Polyhistor/BD-and-Microservices-#8]
1) abstract: "with 7 experts" --> "with seven experts" (I think numbers up until twelve should be written out, unless there is another "high" number in the same sentence)

2) introduction: "overwhelmed existing system capability" --> maybe "overwhelmed the existing systems' capability"

3) introduction: "BD is the practice of crunching large sets of heterogenous data to discover patterns and insights for business competitive advantage." --> maybe "BD analytics can be described as the practice of crunching large sets of heterogenous data to discover patterns and insights for business competitive advantage."

4) contributions: "conducted the interviews. Daniel Staegemann has done quality checks and revised parts of the manuscript" --> wrong name

5) authors' information: not sure if it makes sense to remove the ", born in 1989 in Berlin," so the structure of our texts is a bit more similar

6) 6.1: "Our SSI methodology is made up of four phases: 1) identifying the rationale for using semi-structured interviews, 2) formulating the preliminary semi-structured interview guide, 3) pilot testing the interview guide, 4) presenting the results of the interview." --> I think between 3 and 4 should be another phase "conducting the interviews"

7) 6.1: "because our conceptual framework is made up of" --> in the sentence before is also "made up" used. Maybe replace one with comprised of/comprises

8) 6.1: " These leads can be" --> maybe " These can subsequently be" (to not have "lead" 2 times in 3 words)

9) 6.1: "new ideas, and allow for participant-orientation." --> I think "new ideas and allow for participant-orientation." (without the comma; if it is "linked" to "...explore new ideas") or "new ideas, and allows for participant-orientation." (if it is "linked" to "Our guide is flexible")

10) 6.1: " of our interview which" --> " of our interview, which" (comma)

11) 6.1: "may be deemed eccentric" --> maybe we could add an example for that but not sure about that

12) 6.1: " Follow-up questions were utilized to direct the dialogue towards the subject of our study, and make things easier for candidates to understand. Some of these follow-up questions were improvised, as we did not aim to rigidly control the flow of the interview. " --> I think that should come directly after "as recommended by Kallio et al. [43]. "

13) 6.1: "We pilot tested our interview guide using internal testing, which involved an evaluation of the preliminary interview guide with the members of the research team. We aimed to assume the role of the interviewee and gain insight into the limitations of our
guide." and "After this, to ensure the rigour and relevance of the interview guide, we’ve conducted a pilot test. This step was
necessary to make informed adjustments to the guide, and to improve quality of data collection." --> those parts seem quite redundant

14) interview guide: Why are there spaces in front of the question marks?

15) numbering: "Conclusion" is 8; "Declarations" is 9 (but in small formatting); "Semi-Structured Interview Guide" and "Appendix" have no number, yet in "6.1" it is stated "Our interview guide is available at Appendix 8."

16) 6.2: "We chose purposive sampling because" --> "We chose this approach because" (to avoid repeating purposive sampling)

17) 6.2: " it allowed us to collect rich information by expert sampling" --> wouldn't expert sampling also be possible without "purposive sampling", unlike implied by the statement?

18) 6.2: "candidates from various industries." --> maybe "candidates from various industries and backgrounds." (we also have different countries and people without a bachelors to professors)

19) 6.2: "An overview of these experts are portrayed" --> "An overview of these experts is portrayed"

20) 6.3: "interviews are done" --> I think "interviews were done"

21) 6.3: " Transcripts for each interview has been added to Nvivo and then codes are created." --> " Transcripts for each interview have been added to Nvivo [maybe add the version] and then codes were created."

22) 6.3: "for each BD characteristics" --> "for each BD characteristic"

23) 6.3: "how some of patterns of microservices" --> "how some microservice patterns"

24) 6.3: "These higher level codes were connected to create themes" --> maybe "These were subsequently connected to create themes" (to avoid repeating "higher level codes")

25) 6.4: "with one question from the interviewee " --> what do you mean by that? For me it sounds as if each interviewee had to ask you exactly one question

26) 6.4: "Our interviewees had at least 8 years of experience" --> maybe "Each of our interviewees has at least 8 years of experience"

27) 6.4: "While some had more experience with BD and AI, some others were well-versed in MS architecture." --> I would say "While some have more experience with BD and AI, some others are well-versed in MS architectures." (they currently have those skills and didn't only have them at the time of the interviews)

28) 6.4: "We first asked interviewees" --> "We first asked the interviewees"

29) 6.4: "and then asked them if patterns discussed for each characteristic makes sense" --> "and then asked them if the patterns discussed for each characteristic make sense"

30) 6.4: " We asked every interviewee if they" --> maybe "Further, we asked every interviewee if they" (to avoid starting two sentences in a row with "We asked")

31) 6.4: "We present the result of the interviews in sub-section each associated to the corresponding BD characteristic." --> maybe "We present the results of the interviews in distinct sub-sections each associated to the corresponding BD characteristic."

**Comment by Polyhistor** [comment]
17. expert sampling is a type of purposive sampling, based on Kallio's paper. 

all other comments are addressed.
