### ISSUE TITLE
Some comments up until (including) 6.6

### ISSUE THREAD

**Issue by DanielStaegemann** [Polyhistor/BD-and-Microservices-#9]
1) 6: the order of the characteristics should in my opinion be the same as above in the paper

2) 6.5: "All of the interviewees took the idea of API gateway and gateway offloading naturally, while we had to explore the ’external configuration store’ a bit deeper. We used the idea of Kubernetes ingress to help with elaboration of API gateway." --> a) maybe "All of the interviewees took the idea of API gateway and gateway offloading naturally, while we had to explore the ’external configuration store’ a bit deeper. The idea of Kubernetes ingress was used to help elaborating the API gateway." b) this confuses me a bit because at first you say that API gateway didn't really need explaning and then you elaborate, how you explained it

3) 6.5: "We used AWS load balancer example," --> "We used the AWS load balancer as an example,"

4) 6.5: "and talk about a scenario in a which the developer of the batch processing node or the stream processing node, may need to account for the development, trial and production workloads" --> "and talk about a scenario in which the developer of the batch processing node or the stream processing node may need to account for the development, trial, and production workloads" (some commas changed)

5) 6.5: "have different DNS requirements, and configurations" --> delete comma

6) 6.5: "have trial environments " --> do you mean "how trial environments" (in that part of the text there are many "how"s, making the language a bit repetitive, but maybe in that part it is also okay

7) 6.5: "and how buffers, and Infrastructure may vary." --> as far as I know the comma before and in listings is only used when it's 3 or more items

8) 6.5: "After explaining a scenario, interviewees" --> After explaining a scenario, the interviewees

9) 6.5: " One interviewee mentioned" --> I think if possible we should always attribute the statements to the persons (e.g., "Interviewee i3 mentioned"

10) Table 5: interviewee is lowercase and everything else in the header uppercase

11) 6.5: "different nodes may have different configuration " --> "different nodes may have different configurations"

12) 6.5: "security requirements and how configuration" --> in my opinion "security requirements and how the configuration" or "security requirements and how configurations"

13) 6.5.: "Some interviewees discussed" --> see comment 9

14) 6.5: "Nevertheless, externalized configuration store is not as well understood." --> "However, the externalized configuration store is not as well understood."

15) 6.5: "In one interview, an interviewee discussed" --> see comment 9

16) 6.5: "shallow understanding of why certain pattern is adopted" --> "shallow understanding of why a certain pattern is adopted" or "shallow understanding of why certain patterns are adopted"

17) 6.5: "to keep the pattern comply " --> "to keep the pattern compliant "

18) 6.5: "many of the patterns such as API gateway" --> "many of the patterns, such as API gateway"

19) 6.5: I really like the hightlighting of the key findings through the boxes

20) 6.5: "Another interviewee discussed" --> see comment 9

21) 6.5: "may sound easy to do, but daunting " --> "may sound easy to do, but are daunting "

22) 6.5: "The interviewee explained" --> "The interviewee outlined" (the next sentence also starts with "The interviewee then explained")

23) 6.5: "The interviewee then explained" --> "He then explained"

24) 6.5: "Furthermore, he added how externalized configuration" --> "Furthermore, he added how the externalized configuration"

25) 6.5: "One of the interviewees from insurance and finance sector mentioned" --> "The interviewee from the insurance and finance sector (i5) mentioned"

26) 6.5: "any claims, and while there is a special" --> "any claims, but when there is a special"

27) 6.5: " The interviewee mentioned that scaling forecast is" --> " The interviewee mentioned that scaling forecasts are"

28) 6.5: "The same interviewee from the insurance sector discussed" --> "The same interviewee discussed"

29) 6.5: "reconfigure a service at the fly " --> "reconfigure a service on the fly "

30) 6.5: "in a multi-region operating companies" --> "in a multi-region operating company" or "in multi-region operating companies"

31) 6.5: "but as the number of nodes and configurations increase" --> "but as the number of nodes and configurations increases"

32) 6.5: "Another interiveee from the financial sector has affirmed " --> a) "Another interviewee from the financial sector has affirmed " b) in Table 5 noone else is linked with the financial sector (even though I assume you refer to Erik), so maybe add that to Table 5 c) see comment 9

33) 6.5: " has elaborated that ‘external configuration store’ pattern " --> " has elaborated that the ‘external configuration store’ pattern "

34) 6.5: " through metadata objects, kube-system and Etcd" --> " through metadata objects, kube-system, and Etcd"

35) 6.6: "data engineering architecture, and then justified the idea of competing consumers. We then explored how competing consumers can fail, and how" --> I'm genuinly not sure about the commas before the "and"s

36) 6.6: " and how circuit breaker pattern" --> " and how the circuit breaker pattern"

37) 6.6: "Finally we explored the idea of logging and how tail logging " --> a) "Finally we looked into the idea of logging and how tail logging " b) that sounds as if the idea of logging stuff in general is discussed (not necessarily related to MS or BD)

38) 6.6: "An interviewee challenged the idea of competing consumer " --> see comment 9

39) 6.6: "Circuit breaker helps " --> "The circuit breaker pattern helps "

40) 6.6: "In another interview, interviewee asked about" --> see comment 9

41) 6.6: "We took both feedbacks of ’leader election’ and ’more in-detailed logging approach’ into consideration. We researched deeper into leader election, logging approaches, and distributed tracing. We found leader election a bit hard to justify, as it introduces
a single point of failure, can potentially introduce faulty data as there is only one point of trust, and partial deployments are really hard to apply. We found that benefits of ’leader election’ pattern to be outweighed by the complexity it introduces." --> 4 sentences in a row that start with "We"

42) 6.6: "In another interview, the interviewee " --> a) the same start as for the paragraph before b) see comment 9

43) 6.6: "An interviewee from the insurance sector " --> see comment 9

44) 6.6: "but it’s not always great" --> "but it is not always great"

45) 6.6: " He added there should not be a need for " --> "Further, he added that there should be no need for "

46) 6.6: " as most web servers such as Nginx" --> " as most web servers, such as Nginx"

47) 6.6: "In an another interviewee" --> a)language b) see comment 9

48) 6.6: "challenges of time-sychroonization in log aggregator pattern" --> "challenges of time-synchronization with the log aggregator pattern" [! typos !]

49) 6.6: "who had a background in financial sector," --> "who has a background in the financial sector,"

50) 6.6: "from a large amount of services" --> "from a large number of services"

51) 6.6: "which makes debugging and issue resolution much" --> "which makes debugging and issue resolution take much"

52) 6.6: "can be complementary to log aggregator," --> "can be complementary to the log aggregator,"

53) 6.6: "Services should be ‘self-aware’, capable of reflecting on the issue with right error handling mechanisms." --> "Services should be ‘self-aware’, which means capable of reflecting on issues with right error handling mechanisms."

54) 6.6: "details of implemeting OpenTelemtry for different" --> a) "details of implemeting OpenTelemetry for different" b) I think "OpenTelemetry" needs at least some explanation (maybe 0,5-1 sentence) , since it can't be expected that everyone knows it

55) 6.6: "An interviewee from the telecommunication domain" --> see comment 9

56) 6.6: "decpited the fact" --> "depicted the fact"

57) 6.6: "The candidate discussed that services" --> maybe "He further highlighted that services" ("The candidate" was already the start of the previous sentence and "discuss" was also used there)

58) 6.6: "to processes the data" --> "that process the data"

59) 6.6: "and you may even signal the data producers. But that does not mean" --> maybe "and that this might even be signaled to the data producers. However, that does not necessarily mean"

60) 6.6: "ending you data! " --> I think the exclamation mark might be a bit too much

61) 6.6: "He continued discussing how" --> "He continued to explain how" (to reduce the number of "discuss")

62) 6.6: "The candidate continued discussing that even when services are down, data should still be stored to be processed later." and "Therefore, he suggested that during the failure the incoming data should be stored somewhere to be processed later" --> that's in my opinion redundant

63) 6.6: "Candidate believed that data" --> "The candidate believes that data" (I assume he still holds that opinion)

64) 6.6: "and therefore data architect" --> "and, therefore, data architects"

65) 6.6: "Signaling unavailability of a service, does not always mean that data is not sent into the system." --> "Signaling unavailability of a service [comma deleeted] does not always mean that data is not sent into the system."

**Comment by Polyhistor** [comment]
2. first I say they take it naturally, and then I explain how we've elaborated this pattern and with what examples
3. fixed untill point 8, will return to this soon.

**Comment by Polyhistor** [comment]
all comments addressed, referred to reviewes based on their ID as per the table.
